import { AutoModerationRule } from "../../structures/auto_moderation/Auto_Moderation_Rule.ts";
import {
Channel,
Guild,
  GuildChannel,
  GuildUser,
  Message
} from "../../structures/mod.ts";

export interface GatewayEvents {
  APPLICATION_COMMAND_PERMISSIONS_UPDATE?: any;
  AUTO_MODERATION_RULE_CREATE:AutoModerationRule;
  AUTO_MODERATION_RULE_DELETE:AutoModerationRule;
  AUTO_MODERATION_RULE_UPDATE:AutoModerationRule;
  AUTO_MODERATION_ACTION_EXECUTION: any;
  CHANNEL_CREATE:Channel;
  CHANNEL_DELETE:Channel;
  CHANNEL_EDIT:Channel;
  ENTITLEMENT_CREATE:any;
  ENTITLEMENT_DELETE:any;
  ENTITLEMENT_UPDATE:any;
  GUILD_MEMBER_CREATE:any;
  GUILD_MEMBER_DELETE:any;
  GUILD_MEMBER_UPDATE:any;
  GUILD_ROLE_CREATE:any;
  GUILD_ROLE_DELETE:any;
  GUILD_ROLE_UPDATE:any;
  GUILD_SCHEDULED_EVENT_CREATE:any;
  GUILD_SCHEDULED_EVENT_DELETE:any;
  GUILD_SCHEDULED_EVENT_UPDATE:any;
  GUILD_SOUNDBOARD_SOUND_CREATE:any;
  GUILD_SOUNDBOARD_SOUND_DELETE:any;
  GUILD_SOUNDBOARD_SOUND_UPDATE:any;
  INTEGRATION_CREATE:any;
  INTEGRATION_DELETE:any;
  INTEGRATION_UPDATE:any;
  MESSAGE_CREATE:any;
  MESSAGE_DELETE:any;
  MESSAGE_UPDATE:any;
  STAGE_INSTANCE_CREATE:any;
  STAGE_INSTANCE_DELETE:any;
  STAGE_INSTANCE_UPDATE:any;
  SUBSCRIPITON_CREATE:any;
  SUBSCRIPITON_DELETE:any;
  SUBSCRIPITON_UPDATE:any;
  THREAD_CREATE:any;
  THREAD_DELETE:any;
  THREAD_UPDATE:any;
}

