export const Intents = {
	guilds:0,
	privileged_guild_members:1,
	guild_moderation:2,
	guild_exporesions:3,
	guild_integrations:4,
	guild_webhooks:5,
	guild_invites:6,
	guild_voice_states:7,
	privileged_guild_presences:8,
	guild_messages:9,
	guild_message_reactions:10,
	guild_message_typing:11,
	direct_messages:12,
	direct_messages_reactions:13,
	direct_messages_typing:14,
	privileged_message_content:15,
	guild_scheduled_events:16,
	auto_moderation_configration:17,
	auto_moderation_execution:18,
	guild_message_polls:19,
	direct_message_polls:20,
	all: -1
}